targets:
  $default:
    sources:
      - lib/**
    builders:
      artemis:
        options:
          scalar_mapping:
            - graphql_type: Time
              dart_type: DateTime
          schema_mapping:
            - schema: lib/model/gql/schema.graphql
              queries_glob: lib/model/gql/query/**.graphql
              output: lib/model/gql/graphql_api.dart